name: news_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  equatable: ^2.0.0
  flutter_bloc: ^8.1.1
  google_fonts: ^4.0.4
  http: ^0.13.5
  json_serializable: ^6.1.3
  json_annotation: ^4.8.1
  skeleton_text: ^3.0.0
  intl: ^0.19.0
  url_launcher: ^6.1.14
  mockito: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/